const PublicPaths = {
  HOME: '/',
  LOGIN: '/sign-in',
  SIGN_UP: '/sign-up',
  EX: '/ex',
  SERVICE: '/service',
  SERVICE_BY_ID: (id: string) => `/service/${id}`,
  SERVICE_BY_SPECIALITY: (specId: string) => `/service?specialityId=${specId}`,
  DOCTORS_BY_SERVICE: (serviceId: string) => `/service/${serviceId}/doctors`,
  BOOKING_DETAIL: '/booking/detail/:id',
  MEDICINE: '/Medicine',
  COOPERATE: '/Cooperate',
  PROFILE: '/profile',
  CALENDAR: '/calendar-booking',
  SUPPORT: '/support',
  FORGOTPASSWORD: '/forgot-password',
  SPECIALITY: `/speciality`,
  ABOUT_US: '/about-us',
  ABOUT_FOR_PATIENT: '/about-for-patient',
  ABOUT_F0R_DOCTOR: '/about-for-doctor',
  ABOUT_FOR_CONTACT: '/about-for-contact',
  ABOUT_FOR_cooperation: '/about-for-cooperation',
};

export default PublicPaths;
